app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('account/', include('users.urls')),
    path('garage/', include('garage.urls')),
    path('feedback/', include('feedback.urls')),
    path('cart/', include('cart.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.index, name='index'),
    path('product/', views.product_list, name='product_list'),
    path('product/<slug:slug>/', views.product_card, name='product_card'),
    path('supercategory/', views.supercategory, name='supercategory'),
    path('subcategory/<slug:slug>/', views.subcategory, name='subcategory'),
    path('category/<slug:slug>/', views.category, name='category'),
    path('category/subcategory/<slug:slug>/', views.category_detail, name='category_detail'),
    path('category/', views.category, name='category_all'),
    path('sets/', views.set_all, name='set_all'),
    path('set/<slug:slug>/', views.set_detail, name='set_detail'),
    path('search/', views.search_product_set, name='search'),
    path('hits/', views.hits, name='hits'),

    path('api/product/<slug:slug>/<str:action>/', views.product_api, name='product_api'),
    path('api/set/<slug:slug>/<str:action>/', views.set_api, name='set_api'),
]

product/models.py
from django.db import models
from django.utils import timezone
from .utilities import get_image_filename_category, get_image_filename_product, get_image_filename_set
from garage.models import Model
from .mixins import CatalogMixin


class CategoryManager(models.Manager):
    """Универсальный диспетчер для прокси-модели который позволит задать поведение для Category."""

    def supercategories(self):
        supercategories = self.filter(is_supercategory=True)
        return supercategories

    def subcategories(self):
        return self.filter(is_supercategory=False)

    def supercategories_with_subcategories(self):
        return self.supercategories().prefetch_related('subcategories')

    def get_queryset(self):
        return super().get_queryset().select_related('super_category')


class Category(models.Model):
    """Модель категории"""
    name = models.CharField(max_length=50, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='URL')
    image = models.ImageField(upload_to=get_image_filename_category, blank=True, verbose_name='Изображение')
    is_supercategory = models.BooleanField(default=False, verbose_name='Суперкатегория')
    super_category = models.ForeignKey('SuperCategory', on_delete=models.PROTECT,
                                       null=True, blank=True, limit_choices_to={'is_supercategory': True},
                                       verbose_name='Родительская категория', related_name='subcategories')

    objects = CategoryManager()

    def __str__(self):
        return self.name


class SuperCategory(Category):
    """Прокси-модель для суперкатегорий"""

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.super_category = None
        self.is_supercategory = True
        super().save(*args, **kwargs)

    class Meta:
        proxy = True
        ordering = ['name', 'slug']
        verbose_name = 'Суперкатегория'
        verbose_name_plural = 'Суперкатегории'


class SubCategory(Category):
    """Прокси-модель подкатегории"""

    def __str__(self):
        if self.super_category:
            return f'{self.super_category.name} - {self.name}'
        else:
            return f'{self.name}'

    class Meta:
        proxy = True
        ordering = ['super_category__name', 'name', 'slug']
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'


class Product(models.Model, CatalogMixin):
    """Модель товара"""
    category = models.ForeignKey(SubCategory, on_delete=models.PROTECT, verbose_name='Категория',
                                 related_name='products')
    title = models.CharField(max_length=200, verbose_name='Название товара')
    slug = models.SlugField(max_length=250, unique=True, verbose_name='URL')
    content = models.TextField(verbose_name='Описание товара')
    price = models.FloatField(default=0, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    image = models.ImageField(blank=True, upload_to=get_image_filename_product, verbose_name='Изображение')
    author = models.ForeignKey('users.CustomUser', on_delete=models.CASCADE, verbose_name='Автор',
                               related_name='products')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    def delete(self, *args, **kwargs):
        """Удаление товара вместе с его изображениями с помощью django-cleanup"""
        for ai in self.additionalimage_set.all():
            ai.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['title']

    def __str__(self):
        if len(self.title) > 50:
            return self.title[:50] + '...'
        else:
            return self.title

    @property
    def sku(self):
        return f'AP{str(self.id):>05}'


class AdditionalImage(models.Model):
    """Модель дополнительного изображения товара"""
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    image = models.ImageField(upload_to=get_image_filename_product, verbose_name='Дополнительное изображение')

    class Meta:
        verbose_name = 'Дополнительное изображение'
        verbose_name_plural = 'Дополнительные изображения'


class ProductApplicability(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE, verbose_name='Товар',
                                   related_name='applicability')
    model = models.ManyToManyField(Model, verbose_name='Модель', related_name='applicability_products')

    class Meta:
        verbose_name = 'Применяемость'
        verbose_name_plural = 'Применяемость'

    def __str__(self):
        return f'Применяемость для {self.product.title}'


class HitBase(models.Model):
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')

    class Meta:
        abstract = True


class HitProduct(HitBase):
    """Модель хит товара"""
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Хит товар', related_name='hits')

    class Meta:
        verbose_name = 'Хит товара'
        verbose_name_plural = 'Хиты товаров'
        ordering = ['-created_at']


class HitSet(HitBase):
    """Модель хит комплекта"""
    set_object = models.ForeignKey('Set', on_delete=models.CASCADE, verbose_name='Хит комплект', related_name='hits')

    class Meta:
        verbose_name = 'Хит комплекта'
        verbose_name_plural = 'Хиты комплектов'
        ordering = ['-created_at']


class Set(models.Model, CatalogMixin):
    """Модель комплекта товаров"""
    products = models.ManyToManyField(Product, through='SetProduct', verbose_name='Товары', related_name='sets')
    name = models.CharField(max_length=100, verbose_name='Название сета')
    slug = models.SlugField(max_length=150, unique=True, verbose_name='URL')
    description = models.TextField(verbose_name='Описание сета')
    image = models.ImageField(upload_to=get_image_filename_set, verbose_name='Изображение сета')
    total_price = models.FloatField(default=0, verbose_name='Общая цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    discount = models.FloatField(default=0, verbose_name='Скидка в процентах')

    class Meta:
        verbose_name = 'Комплект'
        verbose_name_plural = 'Комплекты'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_total_price(self):
        """Получение общей цены комплекта со скидкой"""
        from django.db.models import Sum, F
        price = Set.objects.filter(pk=self.pk).annotate(
            individual_price=Sum(
                F('set_products__product__price') * F('set_products__quantity'))).first().individual_price or 0

        return round(price * (1 - self.discount / 100), 0)

    def get_savings(self):
        """Получение скидки на комплект"""
        return self.total_price - self.get_total_price()

    def get_quantity(self):
        """Получение количества комплектов"""
        from django.db.models import Min, F, ExpressionWrapper, IntegerField
        quantity = Set.objects.filter(pk=self.pk).annotate(
            individual_quantity=Min(
                ExpressionWrapper(F('set_products__product__quantity'), output_field=IntegerField()))).first() or 0

        return quantity.individual_quantity


class SetProduct(models.Model):
    """Модель товара в комплекте"""
    set = models.ForeignKey(Set, on_delete=models.CASCADE, verbose_name='Комплект', related_name='set_products')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')

    class Meta:
        verbose_name = 'Товар в комплекте'
        verbose_name_plural = 'Товары в комплекте'

    def __str__(self):
        return f'{self.set.name} - {self.product.title}'


class ProductDescription(models.Model):
    """Модель описания товара"""
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар', related_name='descriptions')
    description_type = models.CharField(max_length=200, verbose_name='Тип описания')
    content = models.TextField(verbose_name='Описание')
    order = models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')

    class Meta:
        verbose_name = 'Описание товара'
        verbose_name_plural = 'Описания товаров'

    def __str__(self):
        return f'{self.description_type} - {self.content}'


class DynamicDescriptionField(models.Model):
    """Модель динамического поля"""
    FIELDS_CHOICES = [('text', 'Текст'), ('number', 'Число'),
                      ('boolean', 'Да/Нет'), ('select', 'Выбор из списка')]

    name = models.CharField(max_length=100, verbose_name='Название поля')
    field_type = models.CharField(max_length=20, choices=FIELDS_CHOICES, verbose_name='Тип поля')
    options = models.JSONField(blank=True, null=True, verbose_name='Опции')

    class Meta:
        verbose_name = 'Динамическое поле'
        verbose_name_plural = 'Динамические поля'

    def __str__(self):
        return f'{self.name}'


class ProductDynamicDescription(models.Model):
    """Модель динамического описания товара"""
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар',
                                related_name='dynamic_descriptions')
    field = models.ForeignKey(DynamicDescriptionField, on_delete=models.CASCADE, verbose_name='Поле',
                              related_name='dynamic_descriptions')
    value = models.TextField(blank=True, null=True, verbose_name='Значение')

    class Meta:
        verbose_name = 'Динамическое описание товара'
        verbose_name_plural = 'Динамические описания товаров'

    def __str__(self):
        return f'{self.product.title} - {self.field.name}'

product/forms.py
from django import forms

from .models import SubCategory, Category, ProductApplicability


class SubCategoryForm(forms.ModelForm):
    """Форма для отображения категорий в админке"""
    super_category = forms.ModelChoiceField(
        queryset=Category.objects.supercategories(),
        empty_label='---',
        label='Надкатегория', required=False
    )
    class Meta:
        model = SubCategory
        fields = ('super_category', 'name', 'slug')



class ProductApplicabilityFormAdmin(forms.ModelForm):
    class Meta:
        model = ProductApplicability
        fields = '__all__'
        widgets = {'model': forms.CheckboxSelectMultiple}

product/templates/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container py-5">
    <!-- Заголовок с хлебными крошками -->
    <nav aria-label="breadcrumb" class="mb-4">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'product:index' %}" class="text-decoration-none">Главная</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Все категории</li>
        </ol>
    </nav>

    <div class="row mb-4">
        <div class="col-12">
            <h1 class="display-5 fw-bold text-center mb-3">Категории товаров</h1>
            <p class="text-muted text-center">Выберите интересующую вас категорию</p>
        </div>
    </div>


    <!-- Список категорий -->
    <div class="row">
        <div class="col-12">
            {% if all_categories %}
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4" id="categoriesGrid">
                {% for category in all_categories %}
                <div class="col category-item" data-name="{{ category.name|lower }}"
                     data-has-image="{% if category.image %}true{% else %}false{% endif %}">
                    <div class="card category-card h-100 border-0 shadow-sm hover-shadow">
                        <div class="card-body">
                            <div class="d-flex align-items-center">
                                {% if category.image %}
                                <div class="category-image me-4">
                                    <img src="{{ category.image.url }}" alt="{{ category.name }}"
                                         class="rounded-3 object-fit-cover" width="80" height="80">
                                </div>
                                {% else %}
                                <div class="category-placeholder me-4">
                                    <div class="bg-light rounded-3 d-flex align-items-center justify-content-center"
                                         style="width: 80px; height: 80px;">
                                        <i class="fas fa-folder-open fa-2x text-muted"></i>
                                    </div>
                                </div>
                                {% endif %}

                                <div class="flex-grow-1">
                                    <h5 class="card-title mb-2">
                                        <a href="{% url 'product:category_detail' category.slug %}"
                                           class="text-decoration-none text-dark stretched-link">
                                            {{ category.name }}
                                        </a>
                                    </h5>

                                    <div class="d-flex align-items-center text-muted small">
                                        <i class="fas fa-box me-1"></i>
                                        <span>{{ category.product_set.count }} товаров</span>
                                    </div>

                                    {% if category.super_category %}
                                    <div class="d-flex align-items-center text-muted small mt-1">
                                        <i class="fas fa-folder me-1"></i>
                                        <span>Входит в: {{ category.super_category.name }}</span>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                        <div class="card-footer bg-transparent border-0 pt-0">
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">
                                    <i class="fas fa-calendar me-1"></i>
                                    {{ category.created_at|date:"d.m.Y" }}
                                </small>

                                <span class="badge {% if category.is_supercategory %}bg-warning{% else %}bg-primary{% endif %}">
                                    {% if category.is_supercategory %}Надкатегория{% else %}Подкатегория{% endif %}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <!-- Состояние пустого списка -->
            <div class="text-center py-5">
                <div class="empty-state">
                    <i class="fas fa-folder-open fa-4x text-muted mb-4"></i>
                    <h4 class="text-muted">Категории не найдены</h4>
                    <p class="text-muted">Пока нет ни одной категории товаров</p>
                    {% if user.is_staff %}
                    <a href="{% url 'admin:product_category_add' %}" class="btn btn-primary mt-3">
                        <i class="fas fa-plus me-2"></i>Добавить категорию
                    </a>
                    {% endif %}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block extra_css %}
<style>
    .category-card {
        transition: all 0.3s ease;
        border-radius: 12px;
    }

    .category-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 8px 25px rgba(0, 0, 0, 0.15) !important;
    }

    .hover-shadow {
        transition: box-shadow 0.3s ease;
    }

    .hover-shadow:hover {
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1) !important;
    }

    .category-image img {
        transition: transform 0.3s ease;
    }

    .category-card:hover .category-image img {
        transform: scale(1.05);
    }

    .stretched-link::after {
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        z-index: 1;
        pointer-events: auto;
        content: "";
        background-color: rgba(0,0,0,0);
    }

    .empty-state {
        opacity: 0.7;
    }

    .breadcrumb {
        background-color: transparent;
        padding: 0;
    }

    .object-fit-cover {
        object-fit: cover;
    }
</style>
{% endblock %}

product/templates/hit_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Хиты продаж - {{ block.super }}{% endblock %}

{% block content %}
<section class="py-5">
    <div class="container">
        <!-- Хлебные крошки -->
        <nav aria-label="breadcrumb" class="mb-4">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'product:index' %}">Главная</a></li>
                <li class="breadcrumb-item active">Хиты продаж</li>
            </ol>
        </nav>

        <!-- Заголовок -->
        <div class="row mb-4">
            <div class="col-12">
                <h1 class="h2 mb-3">Хиты продаж</h1>
                <p class="text-muted">Самые популярные товары и комплекты</p>
            </div>
        </div>


        <!-- Сетка хитов -->
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
            {% for hit in hits %}
            <div class="col">
                <div class="card h-100 shadow-sm position-relative">
                    <!-- Ссылка на товар/комплект -->
                    {% if hit.product %}
                    <a href="{% url 'product:product_card' hit.product.slug %}" class="stretched-link"></a>
                    {% elif hit.set_object %}
                    <a href="{% url 'product:set_detail' hit.set_object.slug %}" class="stretched-link"></a>
                    {% endif %}

                    <!-- Бейдж типа -->
                    <div class="position-absolute top-0 start-0 m-2">
                        {% if hit.product %}
                        <span class="badge bg-primary">
                            <i class="fas fa-box me-1"></i>
                            Товар
                        </span>
                        {% elif hit.set_object %}
                        <span class="badge bg-success">
                            <i class="fas fa-gift me-1"></i>
                            Комплект
                        </span>
                        {% endif %}
                    </div>

                    <!-- Изображение -->
                    <div class="product-image-container" style="height: 200px; overflow: hidden;">
                        {% if hit.product and hit.product.image %}
                        <img src="{{ hit.product.image.url }}"
                             class="card-img-top h-100 object-fit-cover"
                             alt="{{ hit.product.title }}"
                             loading="lazy">
                        {% elif hit.set_object and hit.set_object.image %}
                        <img src="{{ hit.set_object.image.url }}"
                             class="card-img-top h-100 object-fit-cover"
                             alt="{{ hit.set_object.name }}"
                             loading="lazy">
                        {% else %}
                        <div class="d-flex align-items-center justify-content-center h-100 bg-light text-muted">
                            <i class="fas fa-image fa-2x"></i>
                        </div>
                        {% endif %}
                    </div>

                    <!-- Тело карточки -->
                    <div class="card-body">
                        <h6 class="card-title text-dark mb-2">
                            {% if hit.product %}
                            {{ hit.product.title|truncatewords:4 }}
                            {% elif hit.set_object %}
                            {{ hit.set_object.name|truncatewords:4 }}
                            {% endif %}
                        </h6>

                        {% if hit.product and hit.product.content %}
                        <p class="card-text text-muted small mb-2">
                            {{ hit.product.content|truncatewords:8 }}
                        </p>
                        {% elif hit.set_object and hit.set_object.description %}
                        <p class="card-text text-muted small mb-2">
                            {{ hit.set_object.description|truncatewords:8 }}
                        </p>
                        {% endif %}

                        <!-- Цена -->
                        <div class="d-flex justify-content-between align-items-center">
                            <span class="text-primary fw-bold">
                                {% if hit.product %}
                                    {{ hit.product.price }} ₽
                                {% elif hit.set_object %}
                                    {{ hit.set_object.total_price }} ₽
                                {% endif %}
                            </span>
                            <small class="text-muted">
                                <i class="fas fa-star text-warning"></i>
                                4.8
                            </small>
                        </div>
                    </div>

                    <!-- Футер карточки -->
                    <div class="card-footer bg-transparent border-0 pt-0">
                        <small class="text-muted">
                            <i class="fas fa-box me-1"></i>
                            В наличии:
                            {% if hit.product %}
                            {{ hit.product.quantity }} шт.
                            {% elif hit.set_object %}
                            {{ hit.set_object.get_quantity }} шт.
                            {% endif %}
                        </small>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-12">
                <div class="text-center py-5">
                    <i class="fas fa-crown fa-3x text-muted mb-3"></i>
                    <h3>Хиты не найдены</h3>
                    <p class="text-muted">Пока нет популярных товаров или комплектов</p>
                    <a href="{% url 'product:index' %}" class="btn btn-primary">Вернуться в каталог</a>
                </div>
            </div>
            {% endfor %}
        </div>

        <!-- Описание раздела -->
        <div class="mt-5 pt-4 border-top">
            <h3 class="h5">Почему эти товары стали хитами?</h3>
            <p class="text-muted">
                В этом разделе собраны самые популярные товары и комплекты, которые чаще всего выбирают наши покупатели.
                Здесь вы найдете проверенные временем решения и лучшие предложения.
            </p>
        </div>
    </div>
</section>
{% endblock %}

{% block extra_css %}
<style>
    .product-image-container {
        transition: transform 0.3s ease;
    }

    .card:hover .product-image-container {
        transform: scale(1.05);
    }

    .card {
        transition: all 0.3s ease;
    }

    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15) !important;
    }

    .object-fit-cover {
        object-fit: cover;
    }

    .breadcrumb {
        background-color: transparent;
        padding: 0;
    }

    .badge {
        font-size: 0.75rem;
    }

    .alert-info {
        background-color: #d1ecf1;
        border-color: #bee5eb;
        color: #0c5460;
    }
</style>
{% endblock %}

product/templates/search.html
<!-- search.html -->
{% extends "base.html" %}

{% block content %}
<div class="container py-5">
    <!-- Поисковая форма -->
    <div class="row mb-4">
        <div class="col-12">
            <form method="get" action="{% url 'product:search' %}" class="search-form">
                <div class="input-group input-group-lg">
                    <input type="text"
                           name="q"
                           class="form-control"
                           placeholder="Поиск товаров и комплектов..."
                           value="{{ query }}">
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-search me-2"></i>Найти
                    </button>
                </div>
            </form>
        </div>
    </div>

    <!-- Результаты -->
    {% if results %}
    <div class="row mb-4">
        <div class="col-12">
            <h2>Результаты поиска: "{{ query }}"</h2>
            <p class="text-muted">Найдено: {{ total_results }} результатов</p>
        </div>
    </div>

    <!-- Сетка результатов -->
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
        {% for product in results %}
        <div class="col">
            <div class="card h-100 shadow-sm position-relative">
                <!-- Ссылка на товар -->
                <a href="{% url 'product:product_card' product.slug %}" class="stretched-link"></a>

                <!-- Изображение товара -->
                <div class="product-image-container" style="height: 200px; overflow: hidden;">
                    {% if product.image %}
                    <img src="{{ product.image.url }}"
                         class="card-img-top h-100 object-fit-cover"
                         alt="{{ product.title }}"
                         loading="lazy">
                    {% else %}
                    <div class="d-flex align-items-center justify-content-center h-100 bg-light text-muted">
                        <i class="fas fa-image fa-2x"></i>
                    </div>
                    {% endif %}
                </div>

                <!-- Тело карточки -->
                <div class="card-body">
                    <h6 class="card-title text-dark mb-2">
                        {{ product.title|truncatewords:4 }}
                    </h6>

                    {% if product.content %}
                    <p class="card-text text-muted small mb-2">
                        {{ product.content|truncatewords:8 }}
                    </p>
                    {% endif %}

                    <!-- Цена и рейтинг -->
                    <div class="d-flex justify-content-between align-items-center">
                        <span class="text-primary fw-bold">{{ product.price }} ₽</span>
                        <small class="text-muted">
                            <i class="fas fa-star text-warning"></i>
                            4.8
                        </small>
                    </div>
                </div>

                <!-- Футер карточки -->
                <div class="card-footer bg-transparent border-0 pt-0">
                    <small class="text-muted">
                        <i class="fas fa-box me-1"></i>
                        В наличии: {{ product.quantity }} шт.
                    </small>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-12">
            <div class="text-center py-5">
                <i class="fas fa-box-open fa-3x text-muted mb-3"></i>
                <h3>Товары не найдены</h3>
                <p class="text-muted">В этой категории пока нет товаров</p>
                <a href="{% url 'product:index' %}" class="btn btn-primary">Вернуться в каталог</a>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Пагинация -->
    {% if page_obj.has_other_pages %}
    <nav class="mt-5">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?q={{ query }}&page={{ page_obj.previous_page_number }}">
                    Назад
                </a>
            </li>
            {% endif %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?q={{ query }}&page={{ page_obj.next_page_number }}">
                    Вперед
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
    {% endif %}
</div>
<style>
    .card {
        border-radius: 12px;
        transition: all 0.3s ease;
        overflow: hidden;
    }

    .card:hover {
        transform: translateY(-5px);
        box-shadow: 0 8px 25px rgba(0, 0, 0, 0.15) !important;
    }

    .product-image-container {
        transition: transform 0.3s ease;
    }

    .card:hover .product-image-container {
        transform: scale(1.05);
    }

    .object-fit-cover {
        object-fit: cover;
    }

    .card-title {
        font-size: 1rem;
        line-height: 1.4;
        display: -webkit-box;
        -webkit-line-clamp: 2;
        -webkit-box-orient: vertical;
        overflow: hidden;
        min-height: 2.8rem;
    }

    .card-text {
        font-size: 0.9rem;
        display: -webkit-box;
        -webkit-line-clamp: 2;
        -webkit-box-orient: vertical;
        overflow: hidden;
        min-height: 2.4rem;
    }

    .text-primary {
        color: #0d6efd !important;
        font-size: 1.1rem;
    }

    .text-muted {
        color: #6c757d !important;
    }

    .bg-light {
        background-color: #f8f9fa !important;
    }

    /* Адаптивность */
    @media (max-width: 768px) {
        .product-image-container {
            height: 160px;
        }

        .card-title {
            font-size: 0.9rem;
            min-height: 2.4rem;
        }

        .text-primary {
            font-size: 1rem;
        }
    }
</style>
{% endblock %}

product/templates/supercategory_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>